### ISSUE TITLE
index type problem

### ISSUE THREAD

**Issue by wadjih-bencheikh18** [cheminfo/arraybuffer-xml-parser#10]
https://github.com/cheminfo/arraybuffer-xml-parser/blob/74b24ee22a5aa2913217705d4aa9b5d3e52a197d/src/traversableToJSON.js#L63

"options.attributesNodeName" is Boolean cannot be an index

**Comment by lpatiny** [comment]
Indeed it should be a string. Thanks to point this out !

**Comment by lpatiny** [comment]
You should remove the default value (so it undefined if not specified)
