### ISSUE TITLE
Jest fails

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/arraybuffer-xml-parser#12]
@targos I have a problem I can not find the reason.  Jest failed to parse a file.

https://github.com/cheminfo/arraybuffer-xml-parser/runs/5478008815?check_suite_focus=true#step:6:373

Could you help me with this ?

**Comment by targos** [comment]
It's probably because the file is written in JS, but it seems the rest of the project is entirely in TS. I think it will take less time to migrate this file to TypeScript instead of trying to investigate further.

**Comment by lpatiny** [comment]
Problem is solved.
