### ISSUE TITLE
crash chrome page

### ISSUE THREAD

**Issue by mindon** [cheminfo/arraybuffer-xml-parser#14]
i'm trying to parse a huge xml without upload it to server, it crashed
under latest chrome with a 970MB xml file ... 

is it possible parse such a huge xml in browser?

**Comment by lpatiny** [comment]
It depends on the content. If it is small objects it will not be possible because you will exhaust your memory. If it is scientific data that are parsed as typed array it is possible.

I'm thinking about improve this library to have a generator that would allow to parse large array of objects.
