### ISSUE TITLE
Change chunk size

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/arraybuffer-xml-parser#15]
@targos do you have any idea how to change the chunk size of a readableWebStream ?

https://github.com/cheminfo/arraybuffer-xml-parser/blob/7939cc50e4248668ae955716ea6f9978b27121ea/src/__tests__/parseStream.test.ts#L8-L11

For the tests I would like to parse a small file and set the chunk size to 10 bytes to generate a lot of chunks

**Comment by targos** [comment]
I really don't know the API very well, but I haven't found a way.

You could try to create a custom [TransformStream](https://developer.mozilla.org/en-US/docs/Web/API/TransformStream) that splits the data into smaller chunks and do `const readableStream = file.readableWebStream().pipeThrough(yourTransform)`

**Comment by lpatiny** [comment]
Thanks. The TransformStream should do the job to debug this code

https://github.com/cheminfo/arraybuffer-xml-parser/blob/abe475daa8226ea451d0061aaf2820e59b3168fc/src/__tests__/parseStream.test.ts#L8-L29
