### ISSUE TITLE
Typescript Typings?

### ISSUE THREAD

**Issue by vexxvakan** [cheminfo/arraybuffer-xml-parser#6]
I can see that the Repo has the required d.ts file but my VSCode fails to recognise the typings and just says that the corresponding import had no types. Fixed it by declaring the types of yours myself but if it was to work automagically that would be awesome!

**Comment by radvansky-tomas** [comment]
Could not find a declaration file for module 'arraybuffer-xml-parser'

I dont think its fixed :( cant add this package

**Comment by lpatiny** [comment]
I was fixed but not released. Should be ok with 0.5.1

https://github.com/cheminfo/arraybuffer-xml-parser/commit/21e3152968c51ca42463d1bae90a4dbbd11f31a3
