### ISSUE TITLE
eslint problem with TextEncoder

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/arraybuffer-xml-parser#8]
I'm not sure why the eslint tests are failing:

https://github.com/cheminfo/arraybuffer-xml-parser/runs/3955797793#step:5:11

All the packages are up-to-date so I would expect it would take the preferences from 

https://github.com/cheminfo/eslint-config/blob/main/index.js#L9-L12

@targos There is something I don't understand there. If you could help me...

**Comment by targos** [comment]
The list of globals that are shared between node and the browser seems a bit outdated...
https://github.com/sindresorhus/globals/blob/70e594a6f7f5a9ba9692f92a372c1b43f4ba0f0b/globals.json#L1671-L1679

I'll try to open a pull request tomorrow to improve this. In the mean time, you can add this to your configuration:

```yml
env:
  node: true
```

**Comment by lpatiny** [comment]
Seems ok now.
